# Generated by Django 2.1.15 on 2021-08-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210827_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
    ]
